const rates={ceiling2:65,ceiling3:70,tv2:900,tv3:750,box:1200,loft2:900,loft3:950,mirror:850,glass2:80000,glass3:70000,electric:120000,granite:30000,shoe:1200,baskets:40000};
const makeRow=(section,name,l,h,rate,unit='sft',qty=0)=>({section,name,l,h,qty,rate,unit});
const decimal=n=>Math.round(Number(n)*100)/100;
const templateData={
  '2 BHK':[
    ['FALSE CEILING','GYPSUM False Ceiling','','',rates.ceiling2,'sft',1195],['LIVING & DINING','TV Unit with Paneling',11,9,rates.tv2],['LIVING & DINING','Crockery Unit',5,7,rates.box],['LIVING & DINING','Pooja Unit',3,7,rates.box],['LIVING & DINING','Vanity Unit with Paneling',3,7,rates.box],['LIVING & DINING','LED Mirror',2,2,rates.mirror],['M. BEDROOM','Wardrobe',11,7,rates.box],['M. BEDROOM','Loft',11,2,rates.loft2],['M. BEDROOM','LED Mirror',2,5,rates.mirror],['M. BEDROOM','Dressing Unit',3,9,rates.box],['C.BEDROOM','Wardrobe',9,7,rates.box],['C.BEDROOM','Loft',12,2,rates.loft2],['KITCHEN','Under Cabinets',10.2,3,rates.box],['KITCHEN','Middle Cabinets',8,2.5,rates.box],['KITCHEN','Loft',10,2,rates.loft2],['KITCHEN','Kitchen Tandem Baskets (3), Pullout (1), Wicker Baskets (2)','','',rates.baskets,'lot',1],['OTHERS','Profile Glass Doors for Kitchen, Crockery, Pooja Room Door','','',rates.glass2,'lot',1],['OTHERS','Electrical Work for Full house including Ceiling','','',rates.electric,'lot',1],['OTHERS','Granite Work for Pooja unit, Crockery and vanity','','',rates.granite,'lot',1],['OTHERS','Shoe Rack',5,3,rates.shoe]
  ],
  '3 BHK':[
    ['FALSE CEILING','Plain GYPSUM False Ceiling with Putty and Painting','','',rates.ceiling3,'sft',1500],['LIVING & DINING','TV Unit with Paneling',11,9,rates.tv3],['LIVING & DINING','Crockery Unit Under Cabinets',5,3,rates.box],['LIVING & DINING','Crockery Unit above Cabinets',5,2,rates.box],['LIVING & DINING','Pooja Unit',4,7,rates.box],['LIVING & DINING','Vanity Unit',3,7,rates.box],['LIVING & DINING','LED Mirror',2,2,rates.mirror],['M. BEDROOM','Wardrobe',6,7,rates.box],['M. BEDROOM','Loft',6,2,rates.loft3],['M. BEDROOM','LED Mirror',2,5,rates.mirror],['M. BEDROOM','Dressing Storage',4.6,9,rates.box],['C.BEDROOM','Wardrobe',8,7,rates.box],['C.BEDROOM','Loft',8,2,rates.loft3],['G.BEDROOM','Wardrobe',10.9,7,rates.box],['G.BEDROOM','Loft',10.9,2,rates.loft3],['KITCHEN','Under Cabinets',17,3,rates.box],['KITCHEN','Middle Cabinets',14,2.5,rates.box],['KITCHEN','Loft',17,2,rates.loft3],['KITCHEN','Kitchen Tandem Baskets (3), Pullout (1), Wicker Baskets (2)','','',rates.baskets,'lot',1],['OTHERS','Profile Glass Doors for Kitchen, Crockery and Pooja Room Door','','',rates.glass3,'lot',1],['OTHERS','Granite for Crockery unit, Pooja unit, Vanity Unit','','',rates.granite,'lot',1],['OTHERS','Electric Work for Full House including Ceiling','','',rates.electric,'lot',1],['OTHERS','Shoe Rack',5,3,rates.shoe]
  ]
};
function templateFor(bhk){return templateData[bhk].map(data=>makeRow(...data))}
function cleanOcrText(value){return String(value||'').replace(/[′`^]/g,"'").replace(/[″$]/g,'"').replace(/[–—]/g,'-').replace(/[×*]/g,'x')}
function planNumber(value){const text=cleanOcrText(value).replace(/[Oo]/g,'0');const match=text.match(/(\d+(?:\.\d+)?)(?:\s*(?:'|ft)?\s*-\s*(\d{1,2})(?:[½¼¾])?\s*(?:\"|in)?)?/i);if(!match)return 0;return match[2]===undefined?decimal(match[1]):Number(`${match[1]}.${match[2]}`)}
function roomLabel(value){const text=value.toLowerCase().replace(/\s+/g,' ');if(/master|m\.?\s*bed/.test(text))return 'M. Bedroom';if(/child|c\.?\s*bed/.test(text))return 'C. Bedroom';if(/guest|g\.?\s*bed/.test(text))return 'G. Bedroom';const numbered=text.match(/bedroom\s*[- ]?([1-5])/);if(numbered)return `Bedroom ${numbered[1]}`;if(/bedroom/.test(text))return 'Bedroom';if(/kitchen/.test(text))return 'Kitchen';if(/living|drawing/.test(text))return 'Living';if(/dining/.test(text))return 'Dining';return value}
function dimensionPairs(text){const dim="(\\d{1,2}(?:\\.\\d+)?(?:\\s*(?:'|ft)?\\s*-\\s*\\d{1,2}(?:[½¼¾])?\\s*(?:\\\"|in)?)?)";const rx=new RegExp(`${dim}\\s*[xX×]\\s*${dim}`,'gi');const pairs=[];let match;while((match=rx.exec(cleanOcrText(text)))){const l=planNumber(match[1]),h=planNumber(match[2]);if(l>=3&&l<=30&&h>=3&&h<=30)pairs.push({l,h,index:match.index})}return pairs}
const roomPattern=/M\.?\s*Bedroom|C\.?\s*Bedroom|G\.?\s*Bedroom|Master Bedroom|Children(?:'s)? Bedroom|Guest Bedroom|Bedroom\s*[- ]?[1-5]?|Kitchen|Living(?: Room| Hall)?|Drawing|Dining/gi;
function makePlanMeta(text){const source=cleanOcrText(text).replace(/[\r\n]+/g,' ').replace(/\s+/g,' ');const result={bhk:null,area:0,rooms:[],pairs:dimensionPairs(source)};const bhk=source.match(/(\d)\s*B\s*H\s*K|\bVilla\b/i);if(bhk)result.bhk=/villa/i.test(bhk[0])?'Villa':`${bhk[1]} BHK`;const builtup=source.match(/([\d,]{3,6})\s*(?:SFT|SQ\.?\s*FT|SQFT)/i);if(builtup)result.area=Number(builtup[1].replace(/,/g,''));return {source,result}}
function uniqueRooms(rooms){const kept=new Map();rooms.forEach(room=>{if(!room||!room.name||!room.l||!room.h)return;const key=`${room.name}:${room.l}:${room.h}`;const saved=kept.get(key);if(!saved||(room.confidence||0)>(saved.confidence||0))kept.set(key,room)});return [...kept.values()]}
function parseText(text){const {source,result}=makePlanMeta(text);let label;while((label=roomPattern.exec(source))){const start=Math.max(0,label.index-40),windowText=source.slice(start,Math.min(source.length,label.index+label[0].length+150));const center=label.index-start+label[0].length/2;const candidates=dimensionPairs(windowText);if(!candidates.length)continue;candidates.sort((a,b)=>{const sa=Math.abs(a.index-center)+(a.index<center?35:0),sb=Math.abs(b.index-center)+(b.index<center?35:0);return sa-sb});const pair=candidates[0];result.rooms.push({name:roomLabel(label[0]),l:pair.l,h:pair.h,confidence:.35})}result.rooms=uniqueRooms(result.rooms);return result}
function distance(a,b,scale){return Math.hypot((a.x-b.x)/scale.w,(a.y-b.y)/scale.h)}
function parseItems(items){const text=textFromItems(items);const plan=parseText(text);const knownNames=new Set(plan.rooms.filter(room=>!/^Bedroom \d+$/.test(room.name)).map(room=>room.name));const usable=items.filter(item=>item&&item.text&&item.centre&&Number.isFinite(item.centre.x)&&Number.isFinite(item.centre.y));if(!usable.length)return plan;const maxX=Math.max(...usable.map(item=>item.centre.x),1),maxY=Math.max(...usable.map(item=>item.centre.y),1),scale={w:maxX,h:maxY};const labels=[];const dimensions=[];usable.forEach((item,index)=>{const close=usable.filter(other=>Math.abs(other.centre.y-item.centre.y)<Math.max(22,maxY*.025)&&Math.abs(other.centre.x-item.centre.x)<maxX*.22).sort((a,b)=>a.centre.x-b.centre.x);const phrase=close.map(other=>other.text).join(' ');for(const candidate of [item.text,phrase]){roomPattern.lastIndex=0;const match=roomPattern.exec(candidate);if(match)labels.push({name:roomLabel(match[0]),point:item.centre});const pairs=dimensionPairs(candidate);pairs.forEach(pair=>dimensions.push({...pair,point:item.centre,index}))}});labels.forEach(label=>{if(/^Bedroom \d+$/.test(label.name)||knownNames.has(label.name))return;const options=dimensions.map(pair=>({...pair,score:distance(label.point,pair.point,scale)})).filter(pair=>pair.score<.22).sort((a,b)=>a.score-b.score);if(options.length){const pair=options[0];plan.rooms.push({name:label.name,l:pair.l,h:pair.h,confidence:Math.max(.55,1-pair.score)})}});plan.rooms=uniqueRooms(plan.rooms);return plan}
function sameDimensions(a,b){return a&&b&&Math.abs(a.l-b.l)<.01&&Math.abs(a.h-b.h)<.01}
function normalizePlan(plan){let fixed=uniqueRooms(plan.rooms);const named=fixed.filter(room=>!/^Bedroom \d+$/.test(room.name));const namedReference=named.filter(room=>room.name!=='Kitchen');fixed=fixed.filter(candidate=>!/^Bedroom \d+$/.test(candidate.name)||!namedReference.some(room=>sameDimensions(room,candidate)));fixed=fixed.filter(room=>room.name!=='Kitchen'||Math.min(room.l,room.h)<=10);const expected=plan.bhk==='3 BHK'?2:plan.bhk==='2 BHK'?1:0;const generic=fixed.filter(room=>/^Bedroom \d+$/.test(room.name));const pool=(plan.pairs||[]).filter(pair=>pair.l*pair.h>=80&&pair.l*pair.h<=190&&!namedReference.some(room=>sameDimensions(room,pair))&&!generic.some(room=>sameDimensions(room,pair)));for(const pair of pool){if(generic.length>=expected)break;generic.push({name:`Bedroom ${generic.length+1}`,l:pair.l,h:pair.h,confidence:.25})}fixed=[...fixed.filter(room=>!/^Bedroom \d+$/.test(room.name)),...generic];delete plan.pairs;plan.rooms=uniqueRooms(fixed);return plan}
function mergePlans(plans){const result={bhk:null,area:0,rooms:[],pairs:[]};plans.forEach(plan=>{if(!result.bhk&&plan.bhk)result.bhk=plan.bhk;if(!result.area&&plan.area)result.area=plan.area;result.pairs.push(...(plan.pairs||[]));plan.rooms.forEach(room=>{const same=result.rooms.find(existing=>existing.name===room.name&&existing.l===room.l&&existing.h===room.h);if(!same)result.rooms.push(room)})});result.rooms=uniqueRooms(result.rooms);return normalizePlan(result)}
function area(room){return room?room.l*room.h:0}
function assignBedrooms(rooms){const beds=rooms.filter(room=>/Bedroom/.test(room.name)).sort((a,b)=>area(b)-area(a));const master=beds.find(room=>room.name==='M. Bedroom')||beds[0];const remaining=beds.filter(room=>room!==master);return {master,child:beds.find(room=>room.name==='C. Bedroom')||remaining[0],guest:beds.find(room=>room.name==='G. Bedroom')||remaining[1]}}
function setMeasurement(lines,section,name,l,h){const item=lines.find(line=>line.section===section&&line.name===name);if(item){item.l=decimal(l);item.h=decimal(h)}}
function applyFormulas(lines,plan){const falseCeiling=lines.find(line=>line.section==='FALSE CEILING');if(falseCeiling&&plan.area)falseCeiling.qty=plan.area;const living=plan.rooms.find(room=>room.name==='Living');if(living)setMeasurement(lines,'LIVING & DINING','TV Unit with Paneling',living.l,living.h);const kitchen=plan.rooms.find(room=>room.name==='Kitchen');if(kitchen){const run=decimal(kitchen.l+kitchen.h);setMeasurement(lines,'KITCHEN','Under Cabinets',run,3);setMeasurement(lines,'KITCHEN','Middle Cabinets',Math.max(1,decimal(run-3)),2.5);setMeasurement(lines,'KITCHEN','Loft',run,2)}const bedrooms=assignBedrooms(plan.rooms);[['M. BEDROOM',bedrooms.master],['C.BEDROOM',bedrooms.child],['G.BEDROOM',bedrooms.guest]].forEach(([section,room])=>{if(!room)return;const wall=Math.min(room.l,room.h);setMeasurement(lines,section,'Wardrobe',wall,7);setMeasurement(lines,section,'Loft',wall,2)})}
function applyPlan(plan){const chosen=plan.bhk||document.getElementById('bhk').value;const bhk=chosen==='2 BHK'?'2 BHK':'3 BHK';document.getElementById('bhk').value=bhk;if(plan.area)document.getElementById('area').value=plan.area;const lines=templateFor(bhk);applyFormulas(lines,plan);const target=typeof quotationRows==='function'?quotationRows():detailRows;target.splice(0,target.length,...lines);rooms=plan.rooms.map(room=>[room.name,room.l,room.h]);const electric=lines.find(line=>/Electrical|Electric Work/.test(line.name));document.getElementById('electric').value=electric.rate;renderRooms();renderRates();update();document.getElementById('preview').hidden=true}
function imageCanvas(file,turn=0){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const scale=Math.min(1,2200/Math.max(image.width,image.height));const width=Math.round(image.width*scale),height=Math.round(image.height*scale),sideways=turn===90||turn===270;const canvas=document.createElement('canvas');canvas.width=sideways?height:width;canvas.height=sideways?width:height;const context=canvas.getContext('2d');context.translate(canvas.width/2,canvas.height/2);context.rotate(turn*Math.PI/180);context.drawImage(image,-width/2,-height/2,width,height);resolve(canvas)};image.onerror=()=>reject(new Error('The image could not be opened'));image.src=reader.result};reader.onerror=()=>reject(new Error('The image could not be read'));reader.readAsDataURL(file)})}
async function pdfCanvas(file){if(!window.pdfjsLib)throw new Error('PDF reader is still loading — please try again');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const page=await pdf.getPage(1);const base=page.getViewport({scale:1});const scale=Math.min(2,2200/Math.max(base.width,base.height));const viewport=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;return canvas}
function enoughRooms(plan){const required=plan.bhk==='2 BHK'?2:3;return plan.rooms.filter(room=>/Bedroom/.test(room.name)).length>=required&&plan.rooms.some(room=>room.name==='Kitchen')}
function textFromItems(items){return items.map(item=>item.text).join('\n')}
async function paddleItems(canvas){if(!window.paddleExtract)throw new Error('Open-source OCR is still loading — please try again in a few seconds');return window.paddleExtract(canvas)}
async function ocrPlan(file){const status=document.getElementById('fileName');try{status.textContent=`${file.name} — preparing the free OCR model…`;const original=file.type==='application/pdf'?await pdfCanvas(file):await imageCanvas(file);status.textContent=`${file.name} — reading labels and measurements on this device…`;const scans=[await paddleItems(original)];let plan=mergePlans(scans.map(parseItems));if(!enoughRooms(plan)&&file.type!=='application/pdf'){for(const turn of [90,270]){status.textContent=`${file.name} — checking a rotated plan view…`;scans.push(await paddleItems(await imageCanvas(file,turn)));plan=mergePlans(scans.map(parseItems));if(enoughRooms(plan))break}}document.getElementById('extract').value=scans.map(textFromItems).join('\n\n--- rotated plan view ---\n\n');applyPlan(plan);status.textContent=`${file.name} — ${plan.rooms.length} room measurement${plan.rooms.length===1?'':'s'} found. Review and correct before generating the quotation.`}catch(error){status.textContent=`${file.name} — ${error.message||'automatic extraction failed'}. You can paste or enter measurements manually.`}}
document.getElementById('file').addEventListener('change',event=>{const file=event.target.files[0];if(file)ocrPlan(file)});
document.getElementById('extractBtn').addEventListener('click',()=>{const plan=parseText(document.getElementById('extract').value);applyPlan(plan);document.getElementById('fileName').textContent=`${plan.bhk||document.getElementById('bhk').value} template applied; review detected measurements`});
