/* Lightweight, local PDF renderer. It needs no third-party service or CDN. */
function pdfQuoteText(value){return String(value??'').replace(/[\r\n]+/g,' ').replace(/[^\x20-\x7e]/g,' ').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function pdfQuoteWrap(value,width,size){const max=Math.max(8,Math.floor(width/(size*.48)));const words=pdfQuoteText(value).split(/\s+/);const lines=[];let line='';words.forEach(word=>{const next=line?`${line} ${word}`:word;if(next.length>max&&line){lines.push(line);line=word}else line=next});if(line)lines.push(line);return lines.length?lines:['']}
function pdfQuoteAmount(value){return `Rs. ${Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
class QuotePdfRenderer{
  constructor(){this.pages=[];this.page(false)}
  page(continued){this.ops=[];this.pages.push(this.ops);this.y=806;this.header= null;this.rect(29,780,34,34,'0.11 0.22 0.18');this.text(37,794,'SV',10,true,'0.90 0.84 0.66');this.text(73,802,'SHREE VISTA INTERIORS',16,true);this.text(73,787,'Where Vision Meets Perfection  |  +91 9154027989',8,false,'0.35 0.43 0.38');this.text(566,802,continued?'ESTIMATED QUOTATION - CONTINUED':'ESTIMATED QUOTATION',9,true,'0.11 0.22 0.18','right');this.line(29,770,566,770,'0.11 0.22 0.18',1.4);this.y=continued?750:748}
  command(value){this.ops.push(value)}
  text(x,y,value,size=9,bold=false,color='0.09 0.13 0.10',align='left'){const t=pdfQuoteText(value);let left=x;if(align==='right')left=x-t.length*size*.48;else if(align==='center')left=x-t.length*size*.24;this.command(`q ${color} rg BT /F${bold?2:1} ${size} Tf 1 0 0 1 ${left.toFixed(2)} ${y.toFixed(2)} Tm (${t}) Tj ET Q`)}
  rect(x,y,w,h,color){this.command(`q ${color} rg ${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f Q`)}
  line(x1,y1,x2,y2,color='0.78 0.84 0.79',width=.5){this.command(`q ${color} RG ${width} w ${x1.toFixed(2)} ${y1.toFixed(2)} m ${x2.toFixed(2)} ${y2.toFixed(2)} l S Q`)}
  cell(x,y,w,h,fill){if(fill)this.rect(x,y-h,w,h,fill);this.command(`q 0.78 0.84 0.79 RG .45 w ${x.toFixed(2)} ${(y-h).toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re S Q`)}
  start(client,location,bhk){this.text(29,this.y,`To: ${client||'Client'}`,10,true);this.y-=15;this.text(29,this.y,location||'Project location',9);this.text(566,this.y,`Date: ${now.toLocaleDateString('en-IN')}`,9,false,'0.09 0.13 0.10','right');this.y-=20;this.text(29,this.y,`Subject: Submission of estimated quotation for your ${bhk} interior works.`,9);this.y-=23}
  ensure(height){if(this.y-height<56){this.page(true);if(this.header)this.tableHeader(this.header.cells,this.header.widths)}}
  tableHeader(cells,widths){this.header={cells,widths};this.ensure(18);let x=29;widths.forEach((width,index)=>{this.cell(x,this.y,width,18,'0.11 0.22 0.18');this.text(x+5,this.y-12,cells[index],8,true,'1 1 1');x+=width});this.y-=18}
  row(cells,widths,options={}){const size=options.size||8;const lines=cells.map((cell,index)=>pdfQuoteWrap(cell,widths[index]-10,size));const count=Math.max(...lines.map(item=>item.length));const height=Math.max(options.minHeight||18,count*(size+3)+8);this.ensure(height);let x=29;widths.forEach((width,index)=>{this.cell(x,this.y,width,height,options.fill);const align=(options.align||[])[index]||'left';lines[index].forEach((line,lineIndex)=>{const yy=this.y-11-lineIndex*(size+3);this.text(align==='right'?x+width-5:x+5,yy,line,size,Boolean(options.bold),options.color||'0.09 0.13 0.10',align)});x+=width});this.y-=height}
  section(label){this.row([label],[537],{fill:'0.91 0.94 0.91',bold:true,size:8,minHeight:18})}
  title(label){this.header=null;this.ensure(27);this.text(29,this.y,label,11,true,'0.11 0.22 0.18');this.line(29,this.y-6,566,this.y-6,'0.78 0.84 0.79');this.y-=18}
  paragraph(lines){this.header=null;lines.forEach(line=>{const wrapped=pdfQuoteWrap(line,530,8.5);this.ensure(wrapped.length*12+2);wrapped.forEach(text=>{this.text(32,this.y,`- ${text}`,8.5);this.y-=12});this.y-=2})}
  signature(){this.header=null;this.ensure(70);this.y-=36;this.line(29,this.y,205,this.y);this.line(391,this.y,566,this.y);this.text(29,this.y-13,'Sumani Sai Reddy. D',8,true);this.text(29,this.y-25,'Shree Vista Interiors',8);this.text(391,this.y-13,'Client Signature',8,true);this.y-=34}
  bytes(){this.pages.forEach((page,index)=>{this.line(29,35,566,35,'0.78 0.84 0.79');this.text(29,23,'Shree Vista Interiors - Estimated quotation',7,false,'0.38 0.45 0.40');this.text(566,23,`Page ${index+1} of ${this.pages.length}`,7,false,'0.38 0.45 0.40','right')});const total=this.pages.length;const font1=3+total*2,font2=font1+1;const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';objects[2]=`<< /Type /Pages /Kids [${this.pages.map((_,i)=>`${3+i*2} 0 R`).join(' ')}] /Count ${total} >>`;this.pages.forEach((ops,index)=>{const pageId=3+index*2,contentId=pageId+1,stream=ops.join('\n');objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`});objects[font1]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';objects[font2]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';let output='%PDF-1.4\n%PDFJS\n';const offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=output.length;output+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const start=output.length;output+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)output+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;output+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return new TextEncoder().encode(output)}
}
function downloadQuotationPdf(){const button=document.getElementById('pdf');const original=button.innerHTML;button.disabled=true;button.textContent='Preparing PDF...';try{const renderer=new QuotePdfRenderer();renderer.start(document.getElementById('client').value,document.getElementById('location').value,document.getElementById('bhk').value);const widths=[31,203,31,31,42,57,38,104];renderer.tableHeader(['S.No','Description','L','H','Qty','Rate','Unit','Cost'],widths);const quoteItems=items();let section='';quoteItems.forEach((item,index)=>{if(item.section!==section){section=item.section;renderer.section(section)}renderer.row([String(index+1),item.name,item.l===''?'-':String(item.l),item.h===''?'-':String(item.h),Number(item.qty).toFixed(1),Number(item.rate).toFixed(2),item.unit,pdfQuoteAmount(item.cost)],widths,{align:['right','left','right','right','right','right','right','right']});const next=quoteItems[index+1];if(!next||next.section!==item.section){const subtotal=quoteItems.filter(row=>row.section===item.section).reduce((sum,row)=>sum+row.cost,0);renderer.row(['SECTION SUB TOTAL','','','','','','',pdfQuoteAmount(subtotal)],widths,{fill:'0.95 0.97 0.95',bold:true,align:['right','left','right','right','right','right','right','right']})}});const grand=quoteItems.reduce((sum,row)=>sum+row.cost,0);renderer.row(['GRAND TOTAL','','','','','','',pdfQuoteAmount(grand)],widths,{fill:'0.11 0.22 0.18',color:'1 1 1',bold:true,align:['right','left','right','right','right','right','right','right'],minHeight:21});renderer.title('Material Description');renderer.tableHeader(['Sl.No','Particulars','Make'],[40,190,307]);materialRows.forEach((material,index)=>renderer.row([String(index+1),material[0],material[1]],[40,190,307],{align:['right','left','left']}));renderer.title('Notes & Payment Terms');renderer.paragraph(['Additional works outside this estimate will be quoted separately.','Quote value may vary with material choices, design changes and confirmed site measurements.','10% token, 30% after design finalization, 30% after shelf and laminate selection, 20% after laminate work, 5% at 90% completion and 5% on handover.','GST extra as applicable.']);renderer.signature();const blob=new Blob([renderer.bytes()],{type:'application/pdf'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=filename('pdf');link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1500)}catch(error){console.error(error);alert('Unable to create the PDF. Please try again.')}finally{button.disabled=false;button.innerHTML=original}}
